services:
	nginx:
		build: ./requirements/nginx/
		container_name: nginx
	mariadb:
		build: ./requirements/mariadb/
		container_name: mariadb
	wordpress:
		build: ./requirements/wordpress/
		container_name: wordpress
