version: '3'

services:
	nginx:
		container_name: nginx
		build: ./requirements/nginx/
		env_file: .env
	mariadb:
		container_name: mariadb
		build: ./requirements/mariadb/
		env_file: .env
	wordpress:
		container_name: wordpress
		build: ./requirements/wordpress/
		env_file: .env
	network:
		
network:

volumes:
