version: "3"

services:
    nginx:
        container_name: nginx
        image: nginx
        build: ./requirements/nginx/
        env_file: .env
        restart: always
        volumes:
            - wordpress:/var/www/wordpress
        networks:
            - inception
        ports:
            - "443:443"
        depends_on:
            - wordpress

    mariadb:
        container_name: mariadb
        image: mariadb
        build: ./requirements/mariadb/
        env_file: .env
        restart: always
        expose:
            - "3306"
        volumes:
            - mariadb:/var/lib/mysql
        networks:
            - inception

    wordpress:
        container_name: wordpress
        image: wordpress
        build: ./requirements/wordpress/
        env_file: .env
        restart: always
        expose:
            - "9000"
        volumes:
            - wordpress:/var/www/wordpress
        networks:
            - inception
        depends_on:
            - mariadb
    
networks:
    inception:
        driver: bridge
    
volumes:
    wordpress:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/champi/data/wordpress'
    mariadb:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/champi/data/mariadb'
